[workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]
preview = ["pixi-build"]

[package]
name = "nanoflann"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-cmake", version = "*" }
# backend = { name = "pixi-build-rattler-build", version = "*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

[tasks.vec-of-vec-example]
description = "Test the vector of vectors example"
cwd = ".pixi/build-v0/nanoflann-o42p_Pgz030/bld/rattler-build_nanoflann/build/bin/"
cmd = "./vector_of_vectors_example"

[dependencies]
nanoflann = {path = "."}
